version: "3.7"
services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: dockerRepo/elasticsearch
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./dockerRepo/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./dockerRepo/elasticsearch/storage:/usr/share/elasticsearch/data:rw
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - http.cors.allow-origin=*
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk

  logstash:
    container_name: logstash
    build:
      context: dockerRepo/logstash
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./data
        target: /elk/data
      - type: bind
        source: ./conf
        target: /elk/conf
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
    ports:
      - "5000:5000"
      - "8088:8088"
      - "8081:8081"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    build:
      context: dockerRepo/kibana
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./dockerRepo/kibana/config:/usr/share/kibana/config
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS="http://elasticsearch:9200"
    networks:
      - elk
    depends_on:
      - elasticsearch
networks:
  elk:
    driver: bridge
